version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "[%(asctime)s] [%(process)d|%(threadName)10s|%(name)s] [%(levelname)s] %(message)s"
  structured_plain:
    (): meltano.core.logging.console_log_formatter
    colors: False
  structured_colored:
    (): meltano.core.logging.console_log_formatter
    colors: True
  key_value:
    (): meltano.core.logging.key_value_formatter
    sort_keys: False
  json:
    (): meltano.core.logging.json_formatter

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: "ext://sys.stderr"
  console_json:
    class: logging.StreamHandler
    level: INFO
    formatter: structured_colored
    stream: "ext://sys.stderr"
  # file:
  #   class: logging.FileHandler
  #   level: INFO
  #   filename: /var/log/meltano.log
  #   formatter: json
loggers:
  airflow:
    processor:
      handlers: [console_json]
      level: INFO
      propogate: False
root:
  level: DEBUG
  propagate: yes
  handlers: [console]