version: 2.1

orbs: 
  heroku: circleci/heroku@1.2.6

jobs:
  build-and-push:
    docker:
      - image: cimg/python:3.10.5
    steps:
    - checkout
    - setup_remote_docker:
        version: 20.10.14
        docker_layer_caching: true
    - run:
        name: "Build Images"
        command: |
          docker build --target scheduler -f Dockerfile -t cooley/airflow-scheduler:lastest .
          docker tag docker.io/cooley/airflow-scheduler:lastest registry.heroku.com/dtech-airflow/scheduler

          docker build --target webserver -f Dockerfile -t cooley/airflow-web:lastest .
          docker tag docker.io/cooley/airflow-web:lastest registry.heroku.com/dtech-airflow/web
    - run:
        name: "Push Images"
        command: |
          docker push registry.heroku.com/dtech-airflow/scheduler
          docker push registry.heroku.com/dtech-airflow/web
  release:
    # docker:
    #   - image: cimg/python:3.10.5
    # steps:
    # - checkout
    # - setup_remote_docker:
    #     version: 20.10.14
    #     docker_layer_caching: true
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/release-docker-image:
          process-types: web scheduler

        


workflows:
  heroku-deploy:
    jobs:
    #  - build-and-push
     - release
        # requires:
        #   - build-and-push