version: 2.1

orbs: 
  heroku: circleci/heroku@1.2.6

jobs:
  build-and-push:
    executor: heroku/default
    # docker:
    #   - image: cimg/python:3.10.5
    steps:
    - heroku/install
    - setup_remote_docker:
        version: 20.10.14
        docker_layer_caching: true
    - checkout
    - run:
        command: ls ~/project
    - restore_cache:
        keys: 
          - v1-deps-{{ checksum "poetry.lock" }}
    - run:
        name: "Build Images"
        command: |
          docker build --target scheduler -f Dockerfile -t cooley/airflow-scheduler:lastest .
          docker tag docker.io/cooley/airflow-scheduler:lastest registry.heroku.com/dtech-airflow/scheduler

          docker build --target webserver -f Dockerfile -t cooley/airflow-web:lastest .
          docker tag docker.io/cooley/airflow-web:lastest registry.heroku.com/dtech-airflow/web
    - save_cache:
        key: v1-deps-{{ checksum "poetry.lock" }}
        paths:
          - ~/.cache/pypoetry/virtualenvs
    - run:
        command: 'heroku container:login'
        name: Login to Heroku Docker image registry
    - run:
        name: "Push Images"
        command: |
          docker push registry.heroku.com/dtech-airflow/scheduler
          docker push registry.heroku.com/dtech-airflow/web
  release:
    executor: heroku/default
    # docker:
    #   - image: cimg/python:3.10.5
    steps:
    - heroku/install
    - checkout
    - setup_remote_docker:
        version: 20.10.14
        docker_layer_caching: true
    - run:
        command: 'heroku container:login'
        name: Login to Heroku Docker image registry
    - run: 
        name: "Push"
        command: heroku container:release -a dtech_airflow web scheduler
    # executor: heroku/default
    # steps:
    #   - checkout
    #   - heroku/install
    #   - heroku/release-docker-image:
    #       process-types: web scheduler

        


workflows:
  heroku-deploy:
    jobs:
     - build-and-push
     - release:
        requires:
          - build-and-push