version: 2.1

orbs: 
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      - image: python:3.8.12-slim
    steps:
    - checkout
    - setup_remote_docker:
        version: 20.10.14
    - run:
        name: "Build Images"
        command: |
          docker build -f Dockerfile.scheduler -t cooley/airflow-scheduler:lastest -f Dockerfile.scheduler .
          docker tag docker.io/cooley/airflow-scheduler:lastest registry.heroku.com/dtech-airflow/scheduler

          docker build -f Dockerfile.web -t cooley/airflow-web:lastest -f Dockerfile.web .
          docker tag docker.io/cooley/airflow-web:lastest registry.heroku.com/dtech-airflow/web


workflows:
  heroku-deploy:
    jobs:
     - build